[project]
name = "mesh-allowance"
authors = ["mesh-protocol-team"]
description = "A decentralized allowance management protocol"
telemetry = false
requirements = []
[contracts.mesh-allowance]
path = "contracts/mesh-allowance.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
